### ISSUE TITLE
哥们儿，你这个效果咋样哈

### ISSUE THREAD

**Issue by Lier007** [guotong1988/text-style-transfer-chinese#2]
拉下来没法跑，少词表 ../tmp/wuxia.vocab

**Comment by yaleimeng** [comment]
新增一个名叫tmp的空目录就可以解决这个报错了。 @Lier007

**Comment by guotong1988** [comment]
效果一般般

**Comment by sgalal** [comment]
想看看最后生成的结果是什么样的

**Comment by daozhi0921** [comment]
报错 ： ValueError: Input 0 of layer gru_cell_2 is incompatible with the layer: its rank is undefined, but the layer requires a defined rank.

**Comment by guotong1988** [comment]
> 报错 ： ValueError: Input 0 of layer gru_cell_2 is incompatible with the layer: its rank is undefined, but the layer requires a defined rank.

TF版本问题

**Comment by daozhi0921** [comment]
我这个后面没用呢， 你做的效果咋样呢？ 
| |
rmx099128
|
|
***@***.***
|
签名由网易邮箱大师定制
在2022年5月27日 ***@***.***> 写道：

Closed #2 as completed.

**Comment by guotong1988** [comment]
https://github.com/guotong1988/text-style-transfer-chinese/issues/1

**Comment by daozhi0921** [comment]
了解了， 请问您训练了多少个epoch呢， 我用的cpu训练，感觉训练还是挺慢的呢~


| |
rmx099128
|
|
***@***.***
|
签名由网易邮箱大师定制
在2022年7月6日 ***@***.***> 写道：

#1
