### ISSUE TITLE
博主，如果有的话麻烦upload到data里，感谢

### ISSUE THREAD

**Issue by Viserion-nlper** [guotong1988/text-style-transfer-chinese#5]
实在是跑不出程序，但又想看下效果 ，着急研究下风格转换 ，感谢

**Comment by guotong1988** [comment]
没了

**Comment by Viserion-nlper** [comment]
> 没了

这个是中文的词向量吗  用glove中文词向量 可以使用吗

**Comment by guotong1988** [comment]
就是每行一个字的词表，可以用 https://storage.googleapis.com/bert_models/2018_11_03/chinese_L-12_H-768_A-12.zip
里的`vocab.txt`
