### ISSUE TITLE
tmp/wuxia.vocab    您方便分享一下吗？

### ISSUE THREAD

**Issue by daozhi0921** [guotong1988/text-style-transfer-chinese#6]
执行main.py  代码时， 缺少wuxia.vocab 文件

**Comment by guotong1988** [comment]
就是每行一个字的词表，可以用 https://storage.googleapis.com/bert_models/2018_11_03/chinese_L-12_H-768_A-12.zip
里的vocab.txt

**Comment by daozhi0921** [comment]
嗯嗯， 好的， 太谢谢你啦~


| |
rmx099128
|
|
***@***.***
|
签名由网易邮箱大师定制
在2022年7月5日 ***@***.***> 写道：

就是每行一个字的词表，可以用 https://storage.googleapis.com/bert_models/2018_11_03/chinese_L-12_H-768_A-12.zip
里的vocab.txt
